checks:
  php:
    code_rating: true
    duplication: true
build:
  environment:
    php: '8.0'

  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
tools:
  php_code_coverage:
    enabled: true
  php_code_sniffer:
    config:
      standard: "PSR12"
  external_code_coverage:
    timeout: 600